
// auto-generated by ThingPulse on Sun May  9 18:00:18 UTC 2021
//
// This database is auto-generated from
//    https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv
//    which is based on the IANA timezone database at
//    https://www.iana.org/time-zones

#pragma once
#include <Arduino.h>

String getTzInfo(const String timezone);
