#pragma once

// =============================================================================
// config_defaults.h — Framework default configuration
// =============================================================================
//
// This file defines the default value for every user-configurable setting.
// DO NOT edit this file directly.
//
// To override any value, copy it into config_override.h and change it there.
// config_override.h is the only file you should ever need to edit.
//
// =============================================================================


// -----------------------------------------------------------------------------
// System
// -----------------------------------------------------------------------------

// Hostname prefix for this device. The chip ID is appended automatically
// to make each device unique (e.g. "weather-display-1a2b3c").
// Used for WiFiManager AP name, mDNS, and ArduinoOTA discovery.
#ifndef CFG_HOSTNAME_PREFIX
  #define CFG_HOSTNAME_PREFIX "weather-display-"
#endif


// -----------------------------------------------------------------------------
// Connectivity — WiFi
// -----------------------------------------------------------------------------
// WiFi credentials are defined in secrets.h, not here.
// See secrets.example.h for the required format.


// -----------------------------------------------------------------------------
// Connectivity — MQTT
// -----------------------------------------------------------------------------
// MQTT credentials (server, username, password, client ID) are defined
// in secrets.h. The port default below can be overridden if your broker
// uses a non-standard port.

// Standard unencrypted MQTT port. Use 8883 for TLS.
#ifndef CFG_MQTT_PORT
  #define CFG_MQTT_PORT 1883
#endif

// MQTT keep-alive interval in seconds.
// How often the client pings the broker to keep the connection alive.
#ifndef CFG_MQTT_KEEPALIVE
  #define CFG_MQTT_KEEPALIVE 30
#endif

// Delay in milliseconds between reconnection attempts if the broker
// connection is lost.
#ifndef CFG_MQTT_RECONNECT_MS
  #define CFG_MQTT_RECONNECT_MS 5000
#endif


// -----------------------------------------------------------------------------
// Connectivity — OTA
// -----------------------------------------------------------------------------
// OTA credentials are defined in secrets.h.


// -----------------------------------------------------------------------------
// Time and Locale
// -----------------------------------------------------------------------------

// POSIX timezone string for your location.
// Full list: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
// Examples:
//   "AEST-10AEDT,M10.1.0,M4.1.0/3"   → Australia/Sydney
//   "EST5EDT,M3.2.0,M11.1.0"          → America/New_York
//   "GMT0BST,M3.5.0/1,M10.5.0"        → Europe/London
//   "UTC0"                            → UTC
#ifndef CFG_TIMEZONE
  #define CFG_TIMEZONE "UTC0"
#endif

// NTP server address. Use a regional pool for better reliability.
// Examples: "pool.ntp.org", "time.google.com", "time.cloudflare.com"
#ifndef CFG_NTP_SERVER
  #define CFG_NTP_SERVER "pool.ntp.org"
#endif

// Display clock in 12-hour (true) or 24-hour (false) format by default.
// The user can also toggle this at runtime by tapping the clock on WeatherScreen.
#ifndef CFG_USE_12HOUR_CLOCK
  #define CFG_USE_12HOUR_CLOCK false
#endif


// =============================================================================
// HARDWARE CONFIGURATION
// =============================================================================
//
// This section uses a hierarchical structure. Enable a capability at the top
// level, then configure its specific settings below.
//
// Only settings relevant to your enabled hardware will be used.
//
// =============================================================================


// -----------------------------------------------------------------------------
// Display — Type and Driver
// -----------------------------------------------------------------------------

// Display driver selection.
// Choose ONE of the following:
//   ILI9341  → 2.4" 240x320 TFT (SPI), common in ESP8266 kits
//   SSD1306  → 128x64 OLED (I2C or SPI), monochrome (not yet implemented)
//   ST7735   → 1.8" 128x160 TFT (SPI) (not yet implemented)
//
// Each driver has its own config file in config/display/ where you can
// adjust driver-specific settings like SPI clock speed and color palette.
#ifndef CFG_DISPLAY_DRIVER
  #define CFG_DISPLAY_DRIVER ILI9341
#endif

// Set to true if a display is physically connected.
// Set to false for headless data-logger builds (future use).
#ifndef CFG_HAS_DISPLAY
  #define CFG_HAS_DISPLAY true
#endif


// -----------------------------------------------------------------------------
// Display — Resolution
// -----------------------------------------------------------------------------
// Physical display resolution in pixels.
// Must match your hardware. Common values:
//   240x320  → ILI9341 2.4" TFT (portrait)
//   128x64   → SSD1306 0.96" OLED
//   128x160  → ST7735 1.8" TFT

#ifndef CFG_SCREEN_WIDTH
  #define CFG_SCREEN_WIDTH 240
#endif
#ifndef CFG_SCREEN_HEIGHT
  #define CFG_SCREEN_HEIGHT 320
#endif


// -----------------------------------------------------------------------------
// Display — Pin Assignments (SPI)
// -----------------------------------------------------------------------------
// ESP8266 GPIO connections to your display.
// D0-D8 are Arduino-style pin names. Check your board's pinout.
//
// MOSI, MISO, SCK are standard SPI pins and don't need to be defined here.

// Data/Command pin: LOW = command, HIGH = data
#ifndef CFG_TFT_DC
  #define CFG_TFT_DC D4
#endif

// Chip Select pin: LOW = select display for SPI communication
#ifndef CFG_TFT_CS
  #define CFG_TFT_CS D2
#endif

// Backlight control pin: typically LOW = on for most TFTs
// Set to -1 if backlight is always on or not controllable
#ifndef CFG_TFT_LED
  #define CFG_TFT_LED D3
#endif


// =============================================================================
// INPUT DEVICES
// =============================================================================
//
// Configure which input methods your hardware supports.
// Only configure settings for devices you've enabled.
//
// =============================================================================


// -----------------------------------------------------------------------------
// Touch Input — Enable/Disable
// -----------------------------------------------------------------------------

// Set to true ONLY if a touch controller is physically connected.
// If false, all touch-related settings below are ignored.
#ifndef CFG_HAS_TOUCH
  #define CFG_HAS_TOUCH true
#endif


// -----------------------------------------------------------------------------
// Touch Input — Type (only relevant if CFG_HAS_TOUCH = true)
// -----------------------------------------------------------------------------
// Set the appropriate type to true based on your hardware.

#ifndef CFG_HAS_RESISTIVE_TOUCH
  #define CFG_HAS_RESISTIVE_TOUCH true
#endif

#ifndef CFG_HAS_CAPACITIVE_TOUCH
  #define CFG_HAS_CAPACITIVE_TOUCH false
#endif


// -----------------------------------------------------------------------------
// Touch Input — Pin Assignments (only relevant if CFG_HAS_TOUCH = true)
// -----------------------------------------------------------------------------
// These pins are ONLY used if CFG_HAS_TOUCH is true.
// For XPT2046 resistive touch controller (common with ILI9341).

// SPI Chip Select for touch controller
#ifndef CFG_TOUCH_CS
  #define CFG_TOUCH_CS D0
#endif

// Interrupt pin (signals when touch is active)
#ifndef CFG_TOUCH_IRQ
  #define CFG_TOUCH_IRQ D1
#endif


// -----------------------------------------------------------------------------
// Touch Input — Behavior (only relevant if CFG_HAS_TOUCH = true)
// -----------------------------------------------------------------------------

// Minimum time in milliseconds between touch events.
// Prevents a single physical touch from generating multiple events.
#ifndef CFG_TOUCH_DEBOUNCE_MS
  #define CFG_TOUCH_DEBOUNCE_MS 50
#endif


// -----------------------------------------------------------------------------
// Touch Calibration (only relevant if CFG_HAS_TOUCH = true)
// -----------------------------------------------------------------------------
// Calibration is ONLY needed for resistive touchscreens.
// Capacitive touch typically doesn't require calibration.

// Set to true to force the calibration workflow on every boot, regardless
// of whether saved calibration data exists on LittleFS.
// Useful during hardware bring-up or after replacing the display.
// Should be false for normal operation.
#ifndef CFG_FORCE_CALIBRATION
  #define CFG_FORCE_CALIBRATION false
#endif

// Filename used to persist touch calibration coefficients on LittleFS.
#ifndef CFG_CALIBRATION_FILE
  #define CFG_CALIBRATION_FILE "/calibration.txt"
#endif


// -----------------------------------------------------------------------------
// Other Input Devices (future)
// -----------------------------------------------------------------------------

// Set to true if physical buttons are connected.
#ifndef CFG_HAS_BUTTONS
  #define CFG_HAS_BUTTONS false
#endif

// Set to true if a rotary encoder is connected.
#ifndef CFG_HAS_ENCODER
  #define CFG_HAS_ENCODER false
#endif


// =============================================================================
// DEVELOPER TOOLS
// =============================================================================


// -----------------------------------------------------------------------------
// Debug Overlay
// -----------------------------------------------------------------------------
//
// When enabled, a two-line diagnostic bar is rendered at the bottom of the
// display after every touch event, showing:
//   Line 1 (yellow) — the mapped InputAction and calibrated screen coordinates
//   Line 2 (blue)   — the raw ADC values from the XPT2046 touch controller
//
// This is useful for diagnosing touch calibration, zone boundaries, and the
// full input pipeline without needing a serial connection.
//
// Disabled by default. Enable in config_override.h by uncommenting:
//   #define DEBUG_OVERLAY
//
// Compiles away completely when not defined — zero overhead in production.
// #define DEBUG_OVERLAY
